### ISSUE TITLE
Invalid library section: Movies

### ISSUE THREAD

**Issue by DerDonCH** [mtimkovich/plex2letterboxd#10]
i follow your instruction, but seem to have the same problem all the time
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/lib/plex2letterboxd/plex2letterboxd/__main__.py", line 4, in <module>
    plex2letterboxd.main()
  File "/var/lib/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 76, in main
    sections = [plex.library.section(s) for s in args.sections]
  File "/var/lib/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 76, in <listcomp>
    sections = [plex.library.section(s) for s in args.sections]
  File "/home/don/.local/lib/python3.8/site-packages/plexapi/library.py", line 73, in section
    raise NotFound(f'Invalid library section: {title}') from None
plexapi.exceptions.NotFound: Invalid library section: Movies
`
What am i doing wrong?

**Comment by DerDonCH** [comment]
No worries, i resolved it.
