### ISSUE TITLE
Possible issue with New Plex Scanner and PlexAPI?

### ISSUE THREAD

**Issue by josephmoyer** [mtimkovich/plex2letterboxd#2]
Tried to run it, but got an error that from my googling of stuff when trying to play around with the PlexAPI, seems to be down for everyone.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/joe/plex2letterboxd/plex2letterboxd/__main__.py", line 4, in <module>
    plex2letterboxd.main()
  File "/home/joe/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 61, in main
    write_csv(sections, args.output)
  File "/home/joe/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 44, in write_csv
    for movie in section.search(sort='lastViewedAt', unwatched=False):
  File "/home/joe/.local/lib/python3.8/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/home/joe/.local/lib/python3.8/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: unwatched
```

Like I'm pretty sure that filter category should be there, but my Movie library is using the newer scanner, so I think it's not gonna work.

**Comment by mtimkovich** [comment]
Thanks for the stack trace, I'll look into it.

**Comment by mtimkovich** [comment]
I'm going to update this to work with the latest API, but as a temporary workaround, you can change:
https://github.com/mtimkovich/plex2letterboxd/blob/4cce42d9919627a55e47beea041cf325ecf18718/setup.py#L15

to:
```py
install_requires=['plexapi==4.2.0']
```

to use the compatible API version. I haven't tested this, though, so I'm working under the assumption nothing's changed on Plex's end.

**Comment by josephmoyer** [comment]
Still bad. I already had plexapi at 4.2.0.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/joe/plex2letterboxd/plex2letterboxd/__main__.py", line 4, in <module>
    plex2letterboxd.main()
  File "/home/joe/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 61, in main
    write_csv(sections, args.output)
  File "/home/joe/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 44, in write_csv
    for movie in section.search(sort='lastViewedAt', unwatched=False):
  File "/home/joe/.local/lib/python3.8/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/home/joe/.local/lib/python3.8/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: unwatched
```

**Comment by josephmoyer** [comment]
I think I got it to work.

Found [this issue](https://github.com/pkkid/python-plexapi/issues/691) over in the plexapi repo, apparently, new server changes broke a lot of stuff. Upgraded my plexapi install to 5.2.0, and plex2letterboxd worked.

**Comment by mtimkovich** [comment]
thanks for fixing the problem for me! ❤️
