### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by nishikan8000** [mtimkovich/plex2letterboxd#8]
i got this after running

`Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib64/python2.7/pkgutil.py", line 475, in find_loader
    loader = importer.find_module(fullname)
  File "/usr/lib64/python2.7/pkgutil.py", line 184, in find_module
    path = [os.path.realpath(self.path)]
  File "/usr/lib64/python2.7/posixpath.py", line 376, in realpath
    return abspath(path)
  File "/usr/lib64/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory`

**Comment by mtimkovich** [comment]
You'll need to be using at least python version 3.6
